### ISSUE TITLE
Remove output files from tree.

### ISSUE THREAD

**Issue by ascherer** [iandennismiller/mueller-report#72]
Instead of placing `.pdf`, `.epub`, etc. files under "version control," the binary results of processing the text sources should be published through regular tagged "releases."

**Comment by iandennismiller** [comment]
One the one hand, I agree completely.  By using GitHub releases, a history of previous releases is created.

On the other hand, by placing the rendered binaries into the /docs path, those files will be published to the website via github pages.

One way to resolve this would be to split the website and document into separate projects.  That way, the document project would not need to be cluttered with the rendered binaries.  As it is, the binaries are causing the .git repo to bloat up...  And nobody will care if the website .git repo is large because most people will never clone the website repo.

Do you know of a way to use github pages to insert alias or redirect links that could map "friendly" URLs onto the releases subsystem?  If we can simply link `/mueller-report.pdf` to the latest release, then I would be happy to stop keeping the binaries in version control.  Otherwise, I probably need to create a separate website repo.

**Comment by ascherer** [comment]
Well, in my clone of the project I have the asset [main.pdf](https://github.com/ascherer/mueller-report/releases/download/PDF.beta/main.pdf) with a canonical URL.
